FROM alaudaDevops/jenkins-2-centos7
USER root
RUN touch /opt/alaudaDevops/configuration/plugins.txt
RUN touch /opt/alaudaDevops/plugins/alaudaDevops-client-plugin.lock
COPY ./jpi /opt/alaudaDevops/plugins
RUN /usr/local/bin/install-plugins.sh /opt/alaudaDevops/configuration/plugins.txt
